-- MySQL Script generated by MySQL Workbench
-- Sat Nov 25 14:22:57 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45),
  `Password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Snippets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Snippets` (
  `ID` INT NOT NULL,
  `Title` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Language` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ratings` (
  `User_ID` INT NOT NULL,
  `Snippet_ID` INT NOT NULL,
  `Safety_Score` FLOAT NOT NULL,
  `Comment` VARCHAR(45) NULL,
  PRIMARY KEY (`User_ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
